add_test(NAME reference-domain COMMAND ${Python3_EXECUTABLE} "${METER_PRODUCT_ROOT}/tests/test_product.py" $<TARGET_FILE:meter-protocol-runner>)
add_test(NAME reference-font COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/generate_fonts.py --product-root ${METER_PRODUCT_ROOT} --check)
add_test(NAME reference-boundary COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_reference_boundary.py)
if(METER_BUILD_UI)
    add_test(NAME reference-smoke COMMAND meter-demo --smoke)
    add_executable(test-reference-ui "${METER_PRODUCT_ROOT}/tests/test_ui.c")
    target_link_libraries(test-reference-ui PRIVATE meter_product meter_platform meter_runtime)
    add_test(NAME reference-ui COMMAND test-reference-ui)
endif()
