#ifndef MIXED_COMMANDS_H
#define MIXED_COMMANDS_H
/** @brief Product 语义命令和瞬时事件身份；不包含 CAN 布局。 */
enum {
    MIXED_EVENT_PDO_TIMEOUT = 0x1001, MIXED_EVENT_SDO_COMPLETE = 0x1002,
    MIXED_EVENT_SYNC_DONE = 0x1003, MIXED_EVENT_SDO_FAILED = 0x1004,
    MIXED_EVENT_PDO_READY = 0x1005, MIXED_EVENT_PARAMETER_A = 0x1006, MIXED_EVENT_PARAMETER_B = 0x1007
};
enum { MIXED_CMD_SET_MAX_SPEED = 101, MIXED_CMD_SET_ACCEL = 102, MIXED_CMD_READ_MAX_SPEED = 103, MIXED_CMD_READ_ACCEL = 104 };
#endif
