# -*- coding: utf-8 -*-
"""构建时生成身份；兼容 SDK OneStep 的 Python 2.7 和主机 Python 3。"""
from __future__ import print_function
import argparse
import hashlib
import json
import os
import subprocess


def _text(data):
    if isinstance(data, bytes):
        return data.decode('utf-8', 'replace')
    return data


def _unicode_line(line):
    if isinstance(line, bytes):
        return line.decode('utf-8')
    return line


def _git(root, *args):
    command = ['git', '-C', root] + list(args)
    if hasattr(subprocess, 'check_output'):
        return _text(subprocess.check_output(command))
    return _text(subprocess.Popen(command, stdout=subprocess.PIPE).communicate()[0])


def revision(root):
    if not root or not os.path.isdir(root):
        return 'unavailable'
    try:
        sha = _git(root, 'rev-parse', 'HEAD').strip()
        status = _git(root, 'status', '--porcelain', '--untracked-files=all')
        if not status:
            return sha
        digest = hashlib.sha256()
        digest.update(status.encode('utf-8'))
        diff = _git(root, 'diff', '--binary', 'HEAD')
        digest.update(diff.encode('utf-8'))
        names = _git(root, 'ls-files', '--others', '--exclude-standard', '-z').split('\0')
        for name in names:
            path = os.path.join(root, name)
            if name and os.path.isfile(path):
                digest.update(name.encode('utf-8'))
                with open(path, 'rb') as stream:
                    digest.update(stream.read())
        return sha + '-dirty-' + digest.hexdigest()[:16]
    except (IOError, OSError, RuntimeError):
        return 'unavailable'


def generate(platform, sdk, board, output):
    values = {'PLATFORM': revision(platform), 'SDK': revision(sdk),
              'LVGL_AIC': revision(os.path.join(platform, 'third_party', 'lvgl-aic')),
              'BOARD': str(board).strip(chr(34))}
    lines = ['/* generated by tools/build_identity.py */',
             '#ifndef METER_BUILD_IDENTITY_H', '#define METER_BUILD_IDENTITY_H']
    lines += ['#define METER_BUILD_' + key + ' ' + json.dumps(value) for key, value in values.items()]
    content = u'\n'.join([_unicode_line(line) for line in lines + ['#endif', '']])
    parent = os.path.dirname(output)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    old = None
    if os.path.isfile(output):
        with open(output, 'rb') as stream:
            old = _text(stream.read())
    if old != content:
        with open(output, 'wb') as stream:
            stream.write(content.encode('utf-8'))
    return values


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--platform', default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    parser.add_argument('--sdk')
    parser.add_argument('--board', default='host')
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.platform, args.sdk, args.board, args.output), indent=2))




