# -*- coding: utf-8 -*-
"""构建时生成身份；兼容 SDK OneStep 的 Python 2.7 和主机 Python 3。"""
from __future__ import print_function
import argparse
import hashlib
import io
import json
import os
import re
import subprocess

try:
    string_types = (basestring,)
except NameError:
    string_types = (str,)


def _text(data):
    if isinstance(data, bytes):
        return data.decode('utf-8', 'replace')
    return data


def _unicode_line(line):
    if isinstance(line, bytes):
        return line.decode('utf-8')
    return line


def _git(root, *args):
    command = ['git', '-C', root] + list(args)
    if hasattr(subprocess, 'check_output'):
        return _text(subprocess.check_output(command))
    return _text(subprocess.Popen(command, stdout=subprocess.PIPE).communicate()[0])


def revision(root):
    if not root or not os.path.isdir(root):
        return 'unavailable'
    try:
        sha = _git(root, 'rev-parse', 'HEAD').strip()
        status = _git(root, 'status', '--porcelain', '--untracked-files=all')
        if not status:
            return sha
        digest = hashlib.sha256()
        digest.update(status.encode('utf-8'))
        diff = _git(root, 'diff', '--binary', 'HEAD')
        digest.update(diff.encode('utf-8'))
        names = _git(root, 'ls-files', '--others', '--exclude-standard', '-z').split('\0')
        for name in names:
            path = os.path.join(root, name)
            if name and os.path.isfile(path):
                digest.update(name.encode('utf-8'))
                with open(path, 'rb') as stream:
                    digest.update(stream.read())
        return sha + '-dirty-' + digest.hexdigest()[:16]
    except (IOError, OSError, RuntimeError):
        return 'unavailable'


def product_identity(product_root):
    """取 Product 声明的构建期标识，优先清单 identity.id，回退到 product.c 的字符串 .id。

    meter_product_t 的 .id 是唯一以字符串初始化的 id（CAN 帧的 .id 是数值），所以这里不做
    完整 C 解析；Product 在 sources.json 里显式声明 identity 后即以清单为准。
    """
    if not product_root or not os.path.isdir(product_root):
        return 'unavailable'
    manifest_path = os.path.join(product_root, 'product', 'sources.json')
    if os.path.isfile(manifest_path):
        try:
            with io.open(manifest_path, encoding='utf-8', errors='replace') as stream:
                manifest = json.load(stream)
        except ValueError:
            manifest = {}
        value = (manifest.get('identity') or {}).get('id')
        if isinstance(value, string_types) and value.strip():
            return value.strip()
    source = os.path.join(product_root, 'product', 'product.c')
    if os.path.isfile(source):
        with io.open(source, encoding='utf-8', errors='replace') as stream:
            match = re.search(r'\.id\s*=\s*"([^"]{1,63})"', stream.read())
        if match:
            return match.group(1)
    return 'unavailable'


def generate(platform, sdk, board, output, product=None):
    values = {'PLATFORM': revision(platform), 'SDK': revision(sdk),
              'LVGL_AIC': revision(os.path.join(platform, 'third_party', 'lvgl-aic')),
              'BOARD': str(board).strip(chr(34))}
    # Python 2.7 与 3 的 dict 迭代顺序不同；按显式键序输出，保证同一输入生成同一头文件。
    keys = ['PLATFORM', 'SDK', 'LVGL_AIC', 'BOARD']
    if product:
        # 身份头此前记录不了选中的 Product，选错产品只能上板才发现。
        values['PRODUCT'] = product_identity(product)
        values['PRODUCT_REVISION'] = revision(product)
        keys += ['PRODUCT', 'PRODUCT_REVISION']
    lines = ['/* generated by tools/build_identity.py */',
             '#ifndef METER_BUILD_IDENTITY_H', '#define METER_BUILD_IDENTITY_H']
    lines += ['#define METER_BUILD_' + key + ' ' + json.dumps(values[key]) for key in keys]
    content = u'\n'.join([_unicode_line(line) for line in lines + ['#endif', '']])
    parent = os.path.dirname(output)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    old = None
    if os.path.isfile(output):
        with open(output, 'rb') as stream:
            old = _text(stream.read())
    if old != content:
        with open(output, 'wb') as stream:
            stream.write(content.encode('utf-8'))
    return values


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--platform', default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    parser.add_argument('--sdk')
    parser.add_argument('--board', default='host')
    parser.add_argument('--product', help='Selected Product root; records its identity and revision')
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.platform, args.sdk, args.board, args.output, args.product), indent=2))




