#!/usr/bin/env python3
"""Generate deterministic synthetic catalogs; --check never edits output."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def generate():
    data = json.loads((ROOT / "schema/demo_catalog.json").read_text(encoding="utf-8"))
    for key, low, high in (("parameters", 8, 15), ("monitors", 10, 20), ("faults", 8, 15)):
        assert low <= len(data[key]) <= high, key
        assert len({row[0] for row in data[key]}) == len(data[key]), f"Duplicate {key}"
    for row in data["parameters"]:
        assert row[3] <= row[5] <= row[4], row
    lines = ['/* Generated by tools/generate_catalog.py; edit schema/demo_catalog.json. */',
             '#include "generated/demo_catalog.h"']
    def array(kind, key, formatter):
        lines.append(f"static const {kind} {key}[] = {{")
        lines.extend("    {" + formatter(row) + "}," for row in data[key])
        lines.append("};")
    q = lambda s: json.dumps(s, ensure_ascii=True)
    array("meter_parameter_def_t", "parameters", lambda r: f'{r[0]}, {q(r[1])}, {q(r[2])}, {float(r[3])}f, {float(r[4])}f, {float(r[5])}f')
    array("meter_monitor_def_t", "monitors", lambda r: f'{q(r[0])}, {q(r[1])}, {r[2]}')
    array("meter_fault_def_t", "faults", lambda r: f'{r[0]}, {q(r[1])}, {q(r[2])}')
    lines.extend(['_Static_assert(sizeof(monitors)/sizeof(monitors[0]) <= METER_MONITOR_CAPACITY, "monitor capacity");',
                  '_Static_assert(sizeof(parameters)/sizeof(parameters[0]) <= METER_PARAMETER_CAPACITY, "parameter capacity");',
                  '_Static_assert(sizeof(faults)/sizeof(faults[0]) <= METER_FAULT_CAPACITY, "fault capacity");',
                  'const meter_catalog_t meter_demo_catalog = {',
                  '    parameters, sizeof(parameters)/sizeof(parameters[0]),',
                  '    monitors, sizeof(monitors)/sizeof(monitors[0]),',
                  '    faults, sizeof(faults)/sizeof(faults[0])', '};', ''])
    target = ROOT / "generated/demo_catalog.c"
    output = "\n".join(lines)
    return target, output

if __name__ == "__main__":
    p = argparse.ArgumentParser(); p.add_argument("--check", action="store_true"); args = p.parse_args()
    target, output = generate()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != output:
            raise SystemExit("Catalog differs; run tools/generate_catalog.py")
    else:
        target.parent.mkdir(exist_ok=True); target.write_text(output, encoding="utf-8", newline="\n")
    print("Synthetic catalog PASS")
